Ensembl/ensembl-web-metadata-api

app/api/models/statistics.py
Species Statistics for triticum aestivum
```
$ curl 'https://beta.ensembl.org/api/metadata/genome/a73357ab-93e7-11ec-a39d-005056b38ce3/stats'
$ {"status_code":500,"details":"Internal Server Error"}
```
On the server side
```
api.resources.metadata:get_metadata_statistics:47 - 1 validation error for GenomeStatistics
non_coding_stats -> nc_average_intron_length
value is not a valid float (type=type_error.float)
```
The data coming out from gRPC may have null values for some stats which is not handled by metadata models. The Pydantic considers  null  as string and tries to convert to whatever type (int,float) which results in an error.
Setting value to None while compiling the data will make pydantic to consider as None and set its value to None. 
```
curl …
```
=> Fix Stats for Triticum Activum

APISpecification.yaml
This PR proposes schemas for the endpoints related to popular species:
- An endpoint to get a list of 42 popular species shown on the main screen of Species Selector.
- An endpoint to return a list of all genomes associated with a given popular species
I've been struggling with the names, both the ones used in proposed url paths and the ones used in schemas. I don't particularly like these names; but I couldn't think of anything better.
https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-2023
Related PR in GitLab: https://gitlab.ebi.ac.uk/ensembl-web/ensembl_search_hub/-/merge_requests/6
=> Add openapi spec for popular species

APISpecification.yaml
1. Added a schema for genome details payload to support [this design](https://xd.adobe.com/view/b8d67194-34d7-40de-bcd9-a3413ea5d727-ed85/screen/12bcb450-f75e-4cca-be29-3edad1760297?fullscreen)
Its typescript equivalent (might be easier to read) is:
```ts
type GenomeDetailedInformation = {
genome_id: string;
genome_tag: string | null;
taxonomy_id: string;
species_taxonomy_id: string; // to be able to retrieve a list of related assemblies
common_name: string | null;
scientific_name: string;
type: {
kind: string;
value: string;
} | null;
is_reference: boolean;
assembly: {
accession_id: string;
name: string;
url: string | null;
};
assembly_provider: {
name: string;
url: string | null;
};
assembly_level: string;
assembly_date: string; // ISO date string in YYYY-MM format
annotation_provider: …
```
=> Add open api  spec for genome details

APISpecification.yaml
Added open api specs for the endpoint that provides karyotype information and the endpoint that validates user input of a region
**Question:** Are [examples in ensembl-2020-genome-search repo](https://github.com/Ensembl/ensembl-2020-genome-search/blob/dev/APISpecification.yaml#L434-L516) valuable, and if yes, how do we carry them over?
https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-2201
=> Add specs for karyotype and region validation

APISpecification.yaml
This PR adds specs for two endpoints:
- An endpoint that disambiguates url path segment that can be either a genome id or a genome tag, and reports back to the client brief information about this genome
- An endpoint that returns example objects for a genome
- https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-2218
- https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-2219
=> Add specs for genome id/tag explainer, and for example objects for a genome

.gitlab-ci.yml, Dockerfile, app/api/models/popular_species.py, app/api/models/statistics.py, app/api/resources/grpc_client.py, app/api/resources/metadata.py, poetry.lock, pyproject.toml, requirements.txt
**This PR**
-  Implements new endpoint /api/metadata/popular_species endpoint
- Refactors the field_name for the stats endpoint due to upstream changes in gRPC message
**Please note that** 
- The data for pseudogene_stats are missung as data is missing in gRPC service - Refer EA-1111
-  homology, variants data is missing in gRPC service as well
**Before merging PR**
- Production Team
- The data on meta-prod-replica should be available (Schema Changes) 
- The packages version for ensembl-metadata-api and Ensembl-metadata-service should be updated for bringing code changes due to schema change
- Web Team
- genome images should be copied to nginx static service - Done by @azangru 
**Related JIRA**
https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-2180 …
=> Popular species & refactoring species_stats

app/api/models/statistics.py
The regulation fields are renamed in the messages coming out of gRPC service.
This PR re maps the fields to the new name
Current Behaviour
```
curl 'https://staging-2020.ensembl.org/api/metadata/genome/a7335667-93e7-11ec-a39d-005056b38ce3/stats' | jq '.genome_stats.regulation_stats'
{
"enhancers": null,
"promoters": null
}
```
With the change 
```
curl 'http://localhost:8014/api/metadata/genome/a7335667-93e7-11ec-a39d-005056b38ce3/stats' | jq '.genome_stats.regulation_stats'
{
"enhancers": 36597,
"promoters": 268483
}
```
=> Update regulation fields

APISpecification.yaml
- For region_validation endpoint, change the term `region` to the term `location`
- Fix response of url explainer endpoint
=> Update OpenAPI spec

app/api/models/statistics.py, app/api/resources/metadata.py
Description
Implement new endpoint example_objects which will return list of objects containing  gene, location, variant example
Related JIRA
https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-2221
See it in Action
```
curl 'https://staging-2020.ensembl.org/api/metadata/genome/a7335667-93e7-11ec-a39d-005056b38ce3/example_objects' | jq
```
Please note  data on _stage is out of date as compared to stage-1 so once it is synced it the actual data will appear
Local using stage-1
```
curl 'http://localhost:8014/api/metadata/genome/a7335667-93e7-11ec-a39d-005056b38ce3/example_objects' \| jq
[
{
"type": "gene",
"id": "ENSG00000221914"
},
{
"type": "location",
"id": "8:26291508-26372680"
}
]
```
=> Example Object endpoint

APISpecification.yaml
Updated stats endpoint to include new statistics from Regulation
See [ENSWBSITES-2213](https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-2213) for attribute names in Production db.
=> Add new fields for regulation stats

APISpecification.yaml, app/api/resources/grpc_client.py, app/api/resources/metadata.py
The PR implements /genome/{slug}/explain endpoint
It uses existing genome models.
- Find out genome_id for the given slug
- get the genome details from genome_id
- filter the results
https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-2220
wheat
```
curl 'http://localhost:8014/api/metadata/genome/iwgsc/explain' | jq                         
{
"genome_id": "a73357ab-93e7-11ec-a39d-005056b38ce3",
"genome_tag": "iwgsc",
"common_name": "bread wheat",
"scientific_name": "Triticum aestivum",
"type": {
"kind": "cultivar",
"value": "Chinese Spring"
},
"is_reference": true,
"assembly": {
"accession_id": "GCA_900519105.1",
"name": "IWGSC"
}
}
```
grch38
```
curl 'http://localhost:8014/api/metadata/genome/grch38/explain' | jq
{
"genome_id": "a7335667-93e7-11ec-a39d-005056b38ce3",
"genome_tag": …
```
=> explain endpoint 

app/api/models/genome.py, app/api/resources/grpc_client.py, app/api/resources/metadata.py
Requesting explain endpoint 
- with slug works
- https://staging-2020.ensembl.org/api/metadata/genome/grch38/explain
```
curl http://localhost:8014/api/metadata/genome/grch38/explain | jq 
{
"genome_id": "a7335667-93e7-11ec-a39d-005056b38ce3",
"genome_tag": "grch38",
"common_name": "human",
"scientific_name": "Homo sapiens",
"type": null,
"is_reference": true,
"assembly": {
"accession_id": "GCA_000001405.29",
"name": "GRCh38.p14"
}
}
```
- with genome_uuid doesn't return anything
- https://staging-2020.ensembl.org/api/metadata/genome/b29f62e6-992e-4049-a26b-b6bd673c51e7/explain
```
curl http://localhost:8014/api/metadata/genome/a7335667-93e7-11ec-a39d-005056b38ce3/explain | jq 
{}
```
The explain endpoint should accept slug or genome_uuid. 
The fix will 
1) consider the input as slug
2) …
=> explain should accept slug or uuid

app/api/models/statistics.py
Added following regulation stats
-  ctcf_count
-  tfbs_count
-  open_chromatin_count
```
curl 'http://localhost:8014/api/metadata/genome/a7335667-93e7-11ec-a39d-005056b38ce3/stats' | jq '.["genome_stats"]["regulation_stats"]'
{
"enhancers": 268483,
"promoters": 36597,
"ctcf_count": 101734,
"tfbs_count": 30873,
"open_chromatin_count": 110623
}
```
[ENSWBSITES-2233](https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-2233)
=> Add regulation stats

app/api/models/genome.py, app/api/models/statistics.py, app/api/resources/metadata.py, requirements.txt
This PR
- Update gRPC version to 0.0.6a6
- With update to 0.0.6a6 the example objects are now available in getGenomeByUUID procedure
- Update example_object to get examples from getGenomeByUUID procedure that iterating over stats endpoint
- Fix issue with annotation provider
```
curl 'http://localhost:8014/api/metadata/genome/a7335667-93e7-11ec-a39d-005056b38ce3/example_objects' | jq
[
{
"type": "gene",
"id": "ENSG00000221914"
},
{
"type": "location",
"id": "8:26291508-26372680"
}
]
```
On Staging it is null 
```
curl 'https://staging-2020.ensembl.org/api/metadata/genome/a7335667-93e7-11ec-a39d-005056b38ce3/details' | jq '.["annotation_provider"]'
null
```
Fix 
```
curl 'http://localhost:8014/api/metadata/genome/a7335667-93e7-11ec-a39d-005056b38ce3/details' | jq '.["annotation_provider"]' …
```
=> Update grpc to 0.0.6a and related refactoring

APISpecification.yaml
In order to be able to show, on the species page, which species homology data has been calculated against (see https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-2288), metadata api will need to include this information in the stats payload.
https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-2316
=> Update metadata stats spec to include reference species name for Compara

species-search-dump/dump_species_search_data_from_metadata.py
This PR is to update the script to use a production owned view instead of the large SQL string. 
It also has the following changes
- removes default value for annotation_provider and annotation_method
- moves annotation_provider to use genbuild_provider to match changes in the database. 
- Improves validation error reporting
- Switches from default assembly to assembly name
=> Updated script to use view instead of hard coded query.

APISpecification.yaml
We are relaxing requirements for the statistics payload, making most fields nullable, because appropriate statistics have not been calculated for some of the genomes.
After a discussion at a code review meeting, we decided the following:
- Any field of the statistics payload is allowed to be nullable. The client will try to make sense of it all.
- It is the responsibility of the backend to sanitise the payload. I.e. there shouldn't be any `"NULL"` or `"NA"` strings in the payload to represent missing data (@ens-st3 says all `"NULL"` strings have been removed from the database)
- There is no longer any need to nullify the whole section (i.e. no need to make `variation_stats` or `regulation_stats` be null.
https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-2213
=> Relax requirements to species stats response

app/api/models/statistics.py
Add homology reference_species to stats endpoint.
https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-2317
```
curl  'http://localhost:8014/api/metadata/genome/1cda6f4c-8f49-4305-b435-5cbe00adec9a/stats'  | jq '.["genome_stats"]["homology_stats"]' 
{
"coverage": 40.7,
"reference_species_name": "Triticum turgidum subsp. durum"
}
```
```
curl 'http://localhost:8014/api/metadata/genome/a7335667-93e7-11ec-a39d-005056b38ce3/stats' | jq '.["genome_stats"]["homology_stats"]'    
{
"coverage": 91.6,
"reference_species_name": "Pan troglodytes"
}
```
(Spoofed the stats in order to produce this)
```
curl "http://localhost:8014/api/metadata/genome/${gid}/stats" | jq '.["genome_stats"]["homology_stats"]'
{
"coverage": null,
"reference_species_name": null
}
```
=> Homology ref species

app/api/resources/metadata.py
Send 500 status code when there is a server error. Currently it sends 404 which is misleading.
https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-2336
In order to produce this Stop grpc Service and try following endpoints
```
$ curl 'http://localhost:8014/api/metadata/genome/a7335667-93e7-11ec-a39d-005056b38ce3/explain' 
{"status_code": 500, "details": "Internal Server Error"}%                                                                                                                                                                              
```
```
$ curl 'http://localhost:8014/api/metadata/genome/a7335667-93e7-11ec-a39d-005056b38ce3/details' 
{"status_code": 500, "details": "Internal Server Error"}
```
=> Handle server error

app/api/models/popular_species.py, app/api/resources/metadata.py, requirements.txt
This PR
1. Update Image URL in the popular_species endpoint 
2. Update grpc version to 0.0.7dev1
```
curl 'https://beta.ensembl.org/api/metadata/popular_species' | jq '.["popular_species"][0]'
{
"species_taxonomy_id": "9606",
"name": "human",
"image": "http://beta.ensembl.org/static/genome_images/9606.svg",
"genomes_count": 99
}
```
```
curl 'https://staging-2020.ensembl.org/api/metadata/popular_species' | jq '.["popular_species"][0]'
{
"species_taxonomy_id": "9606",
"name": "human",
"image": "//staging-2020.ensembl.org/static/genome_images/9606.svg",
"genomes_count": 99
}
```
https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-2343
=> Update image-url & grpc version

requirements.txt
Update ensembl-metadata-service to 0.0.7.dev2, so that it could handle a renamed database field (`ensembl_name` was renamed to `biosample_id`).
=> Update ensembl-metadata-service to 0.0.7.dev2

Dockerfile, requirements.txt
- Upgrade to python 3.11.
- Upgrade dependencies required by metadata api.
- Move from metadata service to metadata API.
=> Upgrade metadata grpc dependencies.

APISpecification.yaml
Update API spec to include new endpoints:
* For fetching FTP file links for a specified genome ([JIRA](https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-2279))
* For fetching the ckecksum for a specified top-level region in a genome ([JIRA](https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-2403))
JIRA: 
- https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-2429
- https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-2423
Examples in the spec:
FTP links:
```
Request: .../api/metadata/genome/3704ceb1-948d-11ec-a39d-005056b38ce3/ftplinks
Response:
[
{
"dataset": "genebuild",
"url": "https://ftp.ebi.ac.uk/pub/databases/ensembl/organisms/Homo_sapiens/GCA_000001405.29/ensembl/genome"
},
{ 
"dataset": "variation",
"url": ...
},
...
]
```
Checksums:
```
Request: …
```
=> Add API spec for FTP links and region checksums

app/api/models/ftplinks.py, app/api/resources/grpc_client.py, app/api/resources/metadata.py, app/core/config.py, requirements.txt
This PR implements Metadata REST API endpoint for fetching FTP download links for a genome.
Maintenance moved to a [separate PR](https://github.com/Ensembl/ensembl-web-metadata-api/pull/43).
JIRA: https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-2430
Test on local machine (grpc service from k8s staging):
`http://localhost:8014/api/metadata/genome/a7335667-93e7-11ec-a39d-005056b38ce3/ftplinks`
```
[
{
"dataset": "variation",
"url": "https://ftp.ebi.ac.uk/pub/databases/ensembl/organisms/Homo_sapiens/GCA_000001405.29/ensembl/variation/GENCODE44"
},
{
"dataset": "regulation",
"url": "https://ftp.ebi.ac.uk/pub/databases/ensembl/organisms/Homo_sapiens/GCA_000001405.29/ensembl/regulation"
},
{
"dataset": "homologies",
"url": "https://ftp.ebi.ac.uk/pub/databases/ensembl/organisms/Homo_sapiens/GC …
```
=> Add FTP links endpoint

APISpecification.yaml, app/api/models/checksums.py, app/api/resources/grpc_client.py, app/api/resources/metadata.py
Add an endpoint to the metadata REST API that accepts the name of a top-level region and returns its sequence checksum.
Jira: [ENSWBSITES-2403](https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-2403)
=> REST API that accepts the name of a top-level region and returns its sequence checksum.

.env.sample, APISpecification.yaml, app/api/models/genome.py, app/core/config.py
MVP will have assemblies tagged as both GCA and GCF, and both the species table and the species pages will need to have links to ENA and NCBI respectively.
The PR uses resolver services https://identifiers.irg to provide URLs for assembly.
https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-2257
```
$ curl 'http://localhost:8014/api/metadata/genome/a7335667-93e7-11ec-a39d-005056b38ce3/details' | jq '.["assembly"]' 
{
"accession_id": "GCA_000001405.29",
"name": "GRCh38.p14",
"url": "https://identifiers.org/insdc.gca/GCA_000001405.29"
}
```
No available
This requires change in the environment variable. Instead of ENA_ASSEMBLY_URL it will need IDENTIFIERS_ORG_BASE_URL. 
Before merging this to main please merge the PR in new-api-config 
To make it consistent across all API …
=> Support GCA/GCF URLs

app/api/resources/grpc_client.py, app/api/resources/metadata.py, app/tests/test_core/test_grpc_connection.py, requirements.txt
Implemented reflection usage to avoid hard dependency with ensembl-metadata-api package version. 
Use reflection instead.
=> Implemented server reflection in GRPCClient

APISpecification.yaml, app/api/models/genome.py, app/api/resources/grpc_client.py, app/api/resources/metadata.py
https://www.ebi.ac.uk/panda/jira/browse/EA-1238
Improved speed by implementing dedicated gRPC calls per endpoint and updated this repo to reflect the changes.
> Can be tested by using this metadata-api tag: https://github.com/Ensembl/ensembl-metadata-api/releases/tag/3.1.0a1
* Kept using `GetGenomeByUUID` gRPC procedure for `/details` API endpoint
* Added `get_attributes_info()` corresponding to `GetAttributesByGenomeUUID` in gRPC for `/example_objects`
* Added `get_brief_genome_details()` corresponding to `GetBriefGenomeDetailsByUUID` in gRPC for `/explain`
* Also removed the use of `get_genome_uuid_from_tag()` and embedded the logic in the gRPC call itself
I ended up creating dedicated gRPC calls for `/example_objects` and `/explain` endpoints, you can see the request and response …
=> Improve speed by implementing dedicated gRPC calls per endpoint

app/api/models/genome.py, app/api/models/statistics.py
* Added `.stats` prefix
* Added `genebuildProviderVersion`
> Both changes are in an `AliasChoices` for a smooth transition without breaking anything
https://www.ebi.ac.uk/panda/jira/browse/EA-1268
This PR can preferably be merged after these two PRs are merged:
=> Add `.stats` Prefix

APISpecification.yaml, app/api/models/genome.py, app/api/resources/grpc_client.py, app/api/resources/metadata.py
To resolve rapid urls with GCA accession, we need an endpoint to fetch this detail from grpc. After consulting with Bilal, we decided to use `GenomeBySpecificKeywordRequest`. This grpc endpoint returns an array of results from which we are picking up genome id and the release version. Release version is used in resolver to sort and find the latest genome id
https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-2830
NA
NA
No
=> Add new grpc endpoint to get genome id from accession id

APISpecification.yaml, app/api/models/vep.py, app/api/resources/grpc_client.py, app/api/resources/metadata.py
Added the endpoint to fetch VEP file paths
https://www.ebi.ac.uk/panda/jira/browse/EA-1309
http://update-vep-paths.review.ensembl.org (I don't know if/how this works)
Request
```
http://0.0.0.0:8014/api/metadata/genome/3704ceb1-948d-11ec-a39d-005056b38ce3/vep/file_path
```
Response
```
{
"faa_location": "Homo_sapiens/GCA_000001405.14/vep/genome/softmasked.fa.bgz",
"gff_location": "Homo_sapiens/GCA_000001405.14/vep/ensembl/geneset/2013_09/genes.gff3.bgz"
}
```
The follwing PR needs to be merged first
* [Meatadata API + gRPC] https://github.com/Ensembl/ensembl-metadata-api/pull/126
=> Add Endpoint to Fetch VEP File Paths

.gitlab-ci.yml, APISpecification.yaml, app/api/models/genome.py, app/api/resources/grpc_client.py, app/api/resources/metadata.py
Add `/releases` endpoint which returns all the releases (for now)
https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-2908
http://add-releases-endpoint.review.ensembl.org/api/metadata/releases
```
/api/metadata/releases
```
```
[
{
"name": "2023-10-18",
"type": "partial",
"is_current": false
},
{
"name": "2024-09-18",
"type": "partial",
"is_current": false
},
{
"name": "2024-10-28",
"type": "partial",
"is_current": false
},
{
"name": "2023-10",
"type": "integrated",
"is_current": true
},
{
"name": "2025-01-16",
"type": "partial",
"is_current": true
},
{
"name": "2025-02-28",
"type": "partial",
"is_current": false
}
]
```
This PR needs to be merged and deployed first: https://github.com/Ensembl/ensembl-metadata-api/pull/128
=> Add releases endpoint

app/api/models/genome.py
https://embl.atlassian.net/browse/ENSPLAT-166
TBD
After the patch:
> Old integrated genome: `/api/metadata/genome/a7335667-93e7-11ec-a39d-005056b38ce3/explain`
```
{
"genome_id": "a7335667-93e7-11ec-a39d-005056b38ce3",
"genome_tag": "grch38",
"common_name": "Human",
"scientific_name": "Homo sapiens",
"type": null,
"is_reference": true,
"assembly": {
"accession_id": "GCA_000001405.29",
"name": "GRCh38.p14"
},
"release": {
"name": "2025-02",
"type": "integrated"
},
"latest_genome": {
"genome_id": "2b5fb047-5992-4dfb-b2fa-1fb4e18d1abb",
"genome_tag": null,           <--- It's null for partial! YAY!
"common_name": "Human",
"scientific_name": "Homo sapiens",
"type": null,
"is_reference": true,
"assembly": {
"accession_id": "GCA_000001405.29",
"name": "GRCh38.p14",
"url": …
```
=> Set `genome_tag` for partial release

app/api/resources/metadata.py
Currently the explain endpoint for metadata rest returns 200 when a non-existent / released genome is queried, this PR fixes the issue
https://embl.atlassian.net/browse/ENSPLAT-187
http://__BRANCH_NAME_HERE__.review.ensembl.org
=> Properly catch 404 in explain endpoint

APISpecification.yaml, app/api/models/genome.py
There wa a bug in Ensembl Beta du to `/explain` not having `species_taxonomy_id` in the response
https://embl.atlassian.net/browse/ENSPLAT-208
TBD
Slack discussion: https://genomes-ebi.slack.com/archives/CC2RKR525/p1750948648601529
```
{
"genome_id": "2b5fb047-5992-4dfb-b2fa-1fb4e18d1abb",
"genome_tag": null,
"common_name": "Human",
"scientific_name": "Homo sapiens",
"species_taxonomy_id": "9606", <---- the newly added field
"type": null,
"is_reference": true,
"assembly": {
"accession_id": "GCA_000001405.29",
"name": "GRCh38.p14"
},
"release": {
"name": "2025-04-28",
"type": "partial"
},
"latest_genome": null
}
```
=> Add `species_taxonomy_id` to `/explain` response

app/api/resources/grpc_client.py
This PR updates the `get_top_level_regions `method to apply a more consistent and meaningful sorting of regions by:
* `rank` (if present): regions without a rank are sorted last.
* `length`: numerically sorted.
[Before](https://beta.ensembl.org/genome-browser/e5a7a144-340f-4455-91ba-5f31e9b47067?focus=gene:SPAC2F7.03c&location=I:532245-539744) ([Endpoint](https://beta.ensembl.org/api/metadata/genome/e5a7a144-340f-4455-91ba-5f31e9b47067/karyotype)):
Vs [After](https://dev-2020.ensembl.org/genome-browser/e5a7a144-340f-4455-91ba-5f31e9b47067?focus=gene:SPAC2F7.03c&location=I:532245-539744) ([Endpoint](https://dev-2020.ensembl.org/api/metadata/genome/e5a7a144-340f-4455-91ba-5f31e9b47067/karyotype)):
https://embl.atlassian.net/wiki/spaces/EPLATFORM/pages/99024950/Beta+10+REST+API+s+Bug+Report#M …
=> Fix Rank Sorting
